name: flutter_weather_icons
description: Flutter package for Weather Icons. Weather Icons is a pack of 222 beautifully crafted Open Source icons for representing weather and climate
version: 1.0.1
author: Rishi Banerjee <rishieric91@gmail.com>
homepage: https://github.com/rshrc/flutter_weather_icons

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^2.0.1

flutter:
  fonts:
    - family: WeatherIcons
      fonts:
        - asset: lib/fonts/weathericons.ttf
